### ISSUE TITLE
rich_rule provider does not see exising rules

### ISSUE THREAD

**Issue by marcofl** [rdo-puppet-modules/puppet-firewalld#14]
rich_rule provider does not find existing rules and updates the zone.xml file every puppet run.

**Comment by iankmor** [comment]
The logs report "rich_rules: rich_rules changed" and lists all  rich_rules.   The zone xml file is updated but the contents don't change.

**Comment by marcofl** [comment]
I'm closing this, as the issue is too old now and I now longer use this module.
